export const ARMOR = {
  padded: {
    id: "padded",
    name: "Padded",
    type: "armor",
    armorClass: 11,
    dexterityLimit: 0,
    strengthRequirement: 0,
    stealthDisadvantage: true,
    weight: 8,
    value: { gp: 5 },
    description: "Light and noisy armor."
  },
  leather: {
    id: "leather",
    name: "Leather",
    type: "armor",
    armorClass: 11,
    dexterityLimit: null,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 10,
    value: { gp: 10 },
    description: "Light armor with manageable protection."
  },
  studded_leather: {
    id: "studded_leather",
    name: "Studded Leather",
    type: "armor",
    armorClass: 12,
    dexterityLimit: null,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 13,
    value: { gp: 45 },
    description: "Reinforced leather armor."
  },
  hide: {
    id: "hide",
    name: "Hide",
    type: "armor",
    armorClass: 12,
    dexterityLimit: 2,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 12,
    value: { gp: 10 },
    description: "Natural hide armor."
  },
  chain_shirt: {
    id: "chain_shirt",
    name: "Chain Shirt",
    type: "armor",
    armorClass: 13,
    dexterityLimit: 2,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 20,
    value: { gp: 50 },
    description: "Light chainmail armor."
  },
  scale_mail: {
    id: "scale_mail",
    name: "Scale Mail",
    type: "armor",
    armorClass: 14,
    dexterityLimit: 2,
    strengthRequirement: 0,
    stealthDisadvantage: true,
    weight: 45,
    value: { gp: 50 },
    description: "Overlapping scales provide protection."
  },
  breastplate: {
    id: "breastplate",
    name: "Breastplate",
    type: "armor",
    armorClass: 14,
    dexterityLimit: 2,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 20,
    value: { gp: 400 },
    description: "A lightweight metal chest armor."
  },
  half_plate: {
    id: "half_plate",
    name: "Half Plate",
    type: "armor",
    armorClass: 15,
    dexterityLimit: 2,
    strengthRequirement: 0,
    stealthDisadvantage: true,
    weight: 40,
    value: { gp: 750 },
    description: "Medium armor with good coverage."
  },
  ring_mail: {
    id: "ring_mail",
    name: "Ring Mail",
    type: "armor",
    armorClass: 14,
    dexterityLimit: 0,
    strengthRequirement: 0,
    stealthDisadvantage: true,
    weight: 40,
    value: { gp: 30 },
    description: "Rings built into leather."
  },
  chain_mail: {
    id: "chain_mail",
    name: "Chain Mail",
    type: "armor",
    armorClass: 16,
    dexterityLimit: 0,
    strengthRequirement: 13,
    stealthDisadvantage: true,
    weight: 55,
    value: { gp: 75 },
    description: "Heavy chain armor."
  },
  splint: {
    id: "splint",
    name: "Splint",
    type: "armor",
    armorClass: 17,
    dexterityLimit: 0,
    strengthRequirement: 15,
    stealthDisadvantage: true,
    weight: 60,
    value: { gp: 200 },
    description: "Solid metal plates."
  },
  plate: {
    id: "plate",
    name: "Plate",
    type: "armor",
    armorClass: 18,
    dexterityLimit: 0,
    strengthRequirement: 15,
    stealthDisadvantage: true,
    weight: 65,
    value: { gp: 1500 },
    description: "The heaviest armor."
  },
  shield: {
    id: "shield",
    name: "Shield",
    type: "armor",
    armorClass: 2,
    dexterityLimit: null,
    strengthRequirement: 0,
    stealthDisadvantage: false,
    weight: 6,
    value: { gp: 10 },
    description: "A handheld shield for +2 AC."
  }
};