export const WEAPONS = {
  club: {
    id: "club",
    name: "Club",
    type: "weapon",
    damage: "1d4",
    damageType: "bludgeoning",
    weight: 2,
    properties: ["light"],
    value: { gp: 0.1 },
    description: "A simple wooden club."
  },
  dagger: {
    id: "dagger",
    name: "Dagger",
    type: "weapon",
    damage: "1d4",
    damageType: "piercing",
    weight: 1,
    properties: ["finesse", "light", "thrown"],
    range: { normal: 20, long: 60 },
    value: { gp: 2 },
    description: "A sharp, pointed blade."
  },
  greatclub: {
    id: "greatclub",
    name: "Greatclub",
    type: "weapon",
    damage: "1d8",
    damageType: "bludgeoning",
    weight: 10,
    properties: ["two-handed"],
    value: { gp: 0.2 },
    description: "A large, heavy club."
  },
  handaxe: {
    id: "handaxe",
    name: "Handaxe",
    type: "weapon",
    damage: "1d6",
    damageType: "slashing",
    weight: 2,
    properties: ["light", "thrown"],
    range: { normal: 20, long: 60 },
    value: { gp: 5 },
    description: "A small axe for throwing or melee."
  },
  javelin: {
    id: "javelin",
    name: "Javelin",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 2,
    properties: ["thrown"],
    range: { normal: 30, long: 120 },
    value: { gp: 0.5 },
    description: "A light spear for throwing."
  },
  light_hammer: {
    id: "light_hammer",
    name: "Light Hammer",
    type: "weapon",
    damage: "1d4",
    damageType: "bludgeoning",
    weight: 2,
    properties: ["light", "thrown"],
    range: { normal: 20, long: 60 },
    value: { gp: 2 },
    description: "A small hammer."
  },
  mace: {
    id: "mace",
    name: "Mace",
    type: "weapon",
    damage: "1d6",
    damageType: "bludgeoning",
    weight: 4,
    properties: [],
    value: { gp: 5 },
    description: "A heavy metal club."
  },
  quarterstaff: {
    id: "quarterstaff",
    name: "Quarterstaff",
    type: "weapon",
    damage: "1d6",
    damageType: "bludgeoning",
    weight: 4,
    properties: ["versatile"],
    versatileDamage: "1d8",
    value: { gp: 0.2 },
    description: "A wooden staff."
  },
  sickle: {
    id: "sickle",
    name: "Sickle",
    type: "weapon",
    damage: "1d4",
    damageType: "slashing",
    weight: 2,
    properties: ["light"],
    value: { gp: 1 },
    description: "A curved farming tool."
  },
  spear: {
    id: "spear",
    name: "Spear",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 3,
    properties: ["thrown", "versatile"],
    range: { normal: 20, long: 60 },
    versatileDamage: "1d8",
    value: { gp: 1 },
    description: "A long pole with a pointed tip."
  },
  crossbow_light: {
    id: "crossbow_light",
    name: "Light Crossbow",
    type: "weapon",
    damage: "1d8",
    damageType: "piercing",
    weight: 5,
    properties: ["ammunition", "loading", "two-handed"],
    range: { normal: 80, long: 320 },
    value: { gp: 25 },
    description: "A small crossbow."
  },
  dart: {
    id: "dart",
    name: "Dart",
    type: "weapon",
    damage: "1d4",
    damageType: "piercing",
    weight: 0.25,
    properties: ["finesse", "thrown"],
    range: { normal: 20, long: 60 },
    value: { gp: 0.05 },
    description: "A small throwing dart."
  },
  shortbow: {
    id: "shortbow",
    name: "Shortbow",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 2,
    properties: ["ammunition", "two-handed"],
    range: { normal: 80, long: 320 },
    value: { gp: 25 },
    description: "A small bow."
  },
  sling: {
    id: "sling",
    name: "Sling",
    type: "weapon",
    damage: "1d4",
    damageType: "bludgeoning",
    weight: 0,
    properties: ["ammunition"],
    range: { normal: 30, long: 120 },
    value: { gp: 0.1 },
    description: "A simple sling for stones."
  },
  battleaxe: {
    id: "battleaxe",
    name: "Battleaxe",
    type: "weapon",
    damage: "1d8",
    damageType: "slashing",
    weight: 4,
    properties: ["versatile"],
    versatileDamage: "1d10",
    value: { gp: 10 },
    description: "A heavy axe for battle."
  },
  flail: {
    id: "flail",
    name: "Flail",
    type: "weapon",
    damage: "1d8",
    damageType: "bludgeoning",
    weight: 2,
    properties: [],
    value: { gp: 10 },
    description: "A spiked ball on a chain."
  },
  glaive: {
    id: "glaive",
    name: "Glaive",
    type: "weapon",
    damage: "1d10",
    damageType: "slashing",
    weight: 6,
    properties: ["heavy", "reach", "two-handed"],
    value: { gp: 20 },
    description: "A polearm with a large blade."
  },
  greataxe: {
    id: "greataxe",
    name: "Greataxe",
    type: "weapon",
    damage: "1d12",
    damageType: "slashing",
    weight: 7,
    properties: ["heavy", "two-handed"],
    value: { gp: 30 },
    description: "A massive two-handed axe."
  },
  greatsword: {
    id: "greatsword",
    name: "Greatsword",
    type: "weapon",
    damage: "2d6",
    damageType: "slashing",
    weight: 6,
    properties: ["heavy", "two-handed"],
    value: { gp: 50 },
    description: "A large two-handed sword."
  },
  halberd: {
    id: "halberd",
    name: "Halberd",
    type: "weapon",
    damage: "1d10",
    damageType: "slashing",
    weight: 6,
    properties: ["heavy", "reach", "two-handed"],
    value: { gp: 20 },
    description: "A polearm with an axe blade."
  },
  lance: {
    id: "lance",
    name: "Lance",
    type: "weapon",
    damage: "1d12",
    damageType: "piercing",
    weight: 6,
    properties: ["reach", "special"],
    value: { gp: 10 },
    description: "A long cavalry lance."
  },
  longsword: {
    id: "longsword",
    name: "Longsword",
    type: "weapon",
    damage: "1d8",
    damageType: "slashing",
    weight: 3,
    properties: ["versatile"],
    versatileDamage: "1d10",
    value: { gp: 15 },
    description: "A classic one-handed sword."
  },
  maul: {
    id: "maul",
    name: "Maul",
    type: "weapon",
    damage: "2d6",
    damageType: "bludgeoning",
    weight: 10,
    properties: ["heavy", "two-handed"],
    value: { gp: 10 },
    description: "A massive hammer."
  },
  morningstar: {
    id: "morningstar",
    name: "Morningstar",
    type: "weapon",
    damage: "1d8",
    damageType: "piercing",
    weight: 4,
    properties: [],
    value: { gp: 15 },
    description: "A spiked club."
  },
  pike: {
    id: "pike",
    name: "Pike",
    type: "weapon",
    damage: "1d10",
    damageType: "piercing",
    weight: 18,
    properties: ["heavy", "reach", "two-handed"],
    value: { gp: 5 },
    description: "A very long spear."
  },
  rapier: {
    id: "rapier",
    name: "Rapier",
    type: "weapon",
    damage: "1d8",
    damageType: "piercing",
    weight: 2,
    properties: ["finesse"],
    value: { gp: 25 },
    description: "A slender fencing sword."
  },
  scimitar: {
    id: "scimitar",
    name: "Scimitar",
    type: "weapon",
    damage: "1d6",
    damageType: "slashing",
    weight: 3,
    properties: ["finesse", "light"],
    value: { gp: 25 },
    description: "A curved sword."
  },
  shortsword: {
    id: "shortsword",
    name: "Shortsword",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 2,
    properties: ["finesse", "light"],
    value: { gp: 10 },
    description: "A short, pointed sword."
  },
  trident: {
    id: "trident",
    name: "Trident",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 4,
    properties: ["thrown", "versatile"],
    range: { normal: 20, long: 60 },
    versatileDamage: "1d8",
    value: { gp: 5 },
    description: "A three-pronged spear."
  },
  war_pick: {
    id: "war_pick",
    name: "War Pick",
    type: "weapon",
    damage: "1d8",
    damageType: "piercing",
    weight: 2,
    properties: [],
    value: { gp: 5 },
    description: "A pick for piercing armor."
  },
  warhammer: {
    id: "warhammer",
    name: "Warhammer",
    type: "weapon",
    damage: "1d8",
    damageType: "bludgeoning",
    weight: 2,
    properties: ["versatile"],
    versatileDamage: "1d10",
    value: { gp: 15 },
    description: "A heavy hammer."
  },
  whip: {
    id: "whip",
    name: "Whip",
    type: "weapon",
    damage: "1d4",
    damageType: "slashing",
    weight: 3,
    properties: ["finesse", "reach"],
    value: { gp: 2 },
    description: "A long leather whip."
  },
  blowgun: {
    id: "blowgun",
    name: "Blowgun",
    type: "weapon",
    damage: "1",
    damageType: "piercing",
    weight: 1,
    properties: ["ammunition", "loading"],
    range: { normal: 25, long: 100 },
    value: { gp: 10 },
    description: "A tube for shooting darts."
  },
  crossbow_hand: {
    id: "crossbow_hand",
    name: "Hand Crossbow",
    type: "weapon",
    damage: "1d6",
    damageType: "piercing",
    weight: 3,
    properties: ["ammunition", "light", "loading"],
    range: { normal: 30, long: 120 },
    value: { gp: 75 },
    description: "A small one-handed crossbow."
  },
  crossbow_heavy: {
    id: "crossbow_heavy",
    name: "Heavy Crossbow",
    type: "weapon",
    damage: "1d10",
    damageType: "piercing",
    weight: 18,
    properties: ["ammunition", "heavy", "loading", "two-handed"],
    range: { normal: 100, long: 400 },
    value: { gp: 50 },
    description: "A large, powerful crossbow."
  },
  longbow: {
    id: "longbow",
    name: "Longbow",
    type: "weapon",
    damage: "1d8",
    damageType: "piercing",
    weight: 2,
    properties: ["ammunition", "heavy", "two-handed"],
    range: { normal: 150, long: 600 },
    value: { gp: 50 },
    description: "A tall bow for long-range shooting."
  },
  net: {
    id: "net",
    name: "Net",
    type: "weapon",
    damage: "0",
    damageType: "special",
    weight: 3,
    properties: ["special", "thrown"],
    range: { normal: 5, long: 15 },
    value: { gp: 1 },
    description: "A net for trapping creatures."
  }
};